# Generated by Django 5.1.4 on 2025-01-04 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordonnance',
            name='dpi',
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='consultation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordonnances', to='base.consultation'),
        ),
    ]
